//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fds_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class empregado
    {
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<int> id_filial { get; set; }
        public Nullable<int> id_setor { get; set; }
        public Nullable<int> id_cargo { get; set; }
    
        public virtual cargo cargo { get; set; }
        public virtual filial filial { get; set; }
        public virtual setor setor { get; set; }
    }
}
